---
title: "Critical Reading of Graphics and Tables Articles"
author: "Andrew Bates"
date: "10/4/2018"
output: pdf_document
---

### Statement 1

> R typically presents output in neatly organized columns and rows with numbers to 4-7 decimal places. It is thus a great idea to use the R output as tables in statistical reports.

#### Response

It's a terrible idea to use that many decimal places in a report table. All three articles state how too many digits makes it difficult for the reader to understand what's going on. One of Ehrenberg's main points is to round "to two effective digits" which he talks about at length. Wainer's *Significance* article agrees. He advocates rounding because "humans cannot comprehend more than two digits very easily." Even in *How to Display Data Badly* which is primarily about graphical displays, Wainer states that "a display can be made clearer by presenting less."

### Statement 2

> The graphic below is an excellent data visualization on Twitter topic traffic.

#### Response 

This statement is just plain false. The graphic is just taking up space as there is only one real number, 45%. It looks like some took Wainer's rules for how to display data badly but dropped the *badly*. For example, it follows *Rule 1 - Show as Few Data as Possible* and *Rule 5 - Graphs Data Out of Context* among others. Wainer's *Significance* article doesn't address graphics, but he would no doubt disagree with the statment. In article, he insists that "a table is for communication." In that vein, he would probably agree that the graphic does not really communicate anything to the reader. Similarly for the Ehrenberg article. He states that "we do not need to learn to read better, but writers need to be taught to write better." With this emphasis on communicating to the reader, one imagines he would disagree with the statement as well.

