---
title: "Stat 696 Old DAR Evaluation"
author: "Andrew Bates"
date: "9/26/2018"
output: html_document
---

### Exam 1

**Rank: 4**

It was not clear to me what analysis was performed in this paper. It's not clear what their model is or even what the response is (maybe average of 4 test scores?). Apparently they used a linear regression model. They presented two tables but I don't understand why there are $\chi^2$ values. This may not be wrong but since it's not the usual regression output, and there is virtually no interpretation, it's confusing. The claim that a better test score in high school is a "free ticket to any colleges" seems to come out of nowhere. If they were analyzing college attendence rate this may have some grounding but this is not mentioned anywhere. Overall, this paper was confusing which makes it hard to read.

There are also a number of issues at a more detailed level. The variable names were all abbreviations that one would need a data dictionary to interpret. The tables were unformatted and look like code output. There were also too many digits in the tables to be readily interpretable. The plot is labeled "Avegrade" which is too brief. The number of bins might be a bit small for the sample size.

They at least tried to provide some interpretation/explanation. But, it was too little to actually understand what they were saying.

### Exam 2

**Rank: **

The first word is a grammatical mistake. It should read *The* instead of *This*. The summary is good in that it provides background, methods, and results. However, they should have expanded a bit more. For example, they say teacher salary and enrollment influence drop-out rate but are these the only variables? "Academic failure" seems a bit too strong of a way to describe drop-out rate. The purpose of the analysis is mentioned at least 3 times on the first page alone (and again in subsequent sections). I'm not sure how controllable the covariates are by a school/school board. The mean drop-out rate is 2. Apparently, this means 2%? Should have explained this.

First paragraph of statistical analysis: I like how the last sentence explains they linear regression was used b/c of interpretability. I like how they provided a brief explanation of backwards elimination but they say variables are removed based on predictive power. Is this a prediction problem or is this an understanding problem? Again, explain early stage models (2 of them) but all the reader cares about is the final model and conclusions. What is a "standardized beta coefficient"? Conclusion: I find it hard to believe that only enrollment and teacher salary influence drop-out rate. Last sentence: if you don't have data to answer your question of interest, why are you trying to answer that question.

Again, the table has too many digits to be readable. The plots in Figure 2: figure titles don't really add anyting that the axis labels don't have.



### Exam 5

**Rank: **

The title has a grammatical error; it should say "relate*d*" and not "relate". I like how this paper has an executive summary to provide a short summary of the problem and results. However, they say they are predicting several different responses, but the paper doesn't explain these models beyond $R^2$. Also, they use $R^2$ as a model selection criteria. In the introduction, I'm not sure what the difference between their usage of "multi-linear" vs. "multivariate". In the additional summary section, they say there are 20 variables, then say 11. They say variable selection was used but don't explain what method was used. Also, they list significant variables but list different variables after model selection. Which ones were used? Writing out the model as an 'equation' doesn't really add anything that the table doesn't provide. The go back and forth between the 'preliminary' model and the 'variable selection' model. Why so many tests for normality (Table 7)? The conclusion is about 1.5 pages while the text for the rest of the paper is about 2 pages. I still don't know what the model is. If they are trying to model a percent, why not use logistic regression?

The tables and figures need reformatting. There are too many digits in the tables, the figures are too small to really analyze, the variable names in the plots are abbreviations and have letters overlapping.


### Exam 11

**Rank: **

Summary: it seems like they're doing several analyses. Which one response are they using? Is this a prediction problem? First sentence of Introduction doesn't seem to imply this.

Intro: "if a difference .. did exist": well did it or did it not? Why did they use "proportional hypothesis testing" for one set of percentages and "hypothesis testing for equal means" for another set? Do we need a table explaining the type of each variable? The number of observations for each when it's stated that there are no missing values? Should be in Appendix if anything.

Statistical Analysis: Normality is not an assumption in a KS test. Did they test normality for **every** varible? Why? How can an average be 100 $\pm$ 20 units? "We have a problem modeling ...": this doesn't make sense. What is the meaning of $\ln (p/(1-p))$? What is $p$? How is logistic regression used if the response is $\in \mathbb{R}$?"This data point was altered ...": WHY!!!.  Don't use code abbreviations for variable names. Table a is code dump. Why $R^2$? Why are you presenting models that aren't your final model? Residual plots say "Log College". I don't remember them stating whether or not a log transform was applied.

What do you mean by "high" and "low"? Is the same method as before (regression) is used, why did you say hypothesis testing in the introduction?






